name: SUPORTEMASTER
title: SUPORTEMASTER - Automatização sob demanda.
description: Bots e soluções inteligentes.
url: https://suportemasterbot.github.io
author: Nilsonlinux
github: https://github.com/Suportemasterbot/
twitter: Nilsonlinux
telegram: Nilsonlinux
mastodon: Nilsonlinux
facebook: Nilsonlinux
reddit: Nilsonlinux
discord: Nilsonlinux
googleAnalyticsId: G-PD6MEPSY43

encoding: utf-8
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]